### ISSUE TITLE
Neovim pyenv issues

### ISSUE THREAD

**Issue by XVicarious** [jceb/vmux#5]
I've set up virtual environments for neovim's python compatibility. Opening the first nvim instance works fine, filename argument or not. The second call to vmux without a filename opens a new nvim, but if I tack a filename on as an argument it tries to attach to nvim, but the module is missing because its using the default environment Python as opposed to neovim's environment.

**Comment by joshbode** [comment]
Is `pynvim` installed in your active virtualenv?

My setup has:
```
$ which python
/Users/josh/.virtualenvs/default/bin/python

$ echo $VIRTUAL_ENV
/Users/josh/.virtualenvs/default

$ pip freeze | grep vim
neovim-remote==2.1.4
pynvim==0.3.2
```

**Comment by joshbode** [comment]
I activate a default virtualenv automatically when I start my shell, but if I deactivate my virtualenv, I get the following:
```
$ deactivate
$ which python
/usr/local/bin/python
$ nvim blah.txt
Traceback (most recent call last):
  File "/Users/josh/.local/bin/vmux", line 496, in main
    return editor_with_session.open(sys.argv[1:])
  File "/Users/josh/.local/bin/vmux", line 212, in open
    from neovim import attach
ModuleNotFoundError: No module named 'neovim'
```

Note: `neovim` is a synonym for `pynvim` and is added if you install `pynvim`

**Comment by jceb** [comment]
Doesn't sound like a vmux issue to me. Is the virtualenv still polluting the environment that vmux is operating in?

**Comment by jceb** [comment]
Issue grew stale.
